### PR TITLE
Chore: ADF-1579 removing lodash4 from ext. as much as possible

### PR DESCRIPTION
**Pull request by Nicholass**
```sh
cd ./extension-tao-delivery
npm audit
```

    found 0 vulnerabilities

After applying the changes the only method left is `_.throttle()`. Used twice:
```sh
ag -l  '_\.' ./extension-tao-delivery
```

    extension-tao-delivery/views/js/controller/runtime/service/deliveryExecution.js
    extension-tao-delivery/views/js/controller/runtime/service/fullScreen.js
    extension-tao-delivery/views/js/loader/deliveryServerIndex.min.js
    extension-tao-delivery/views/js/loader/deliveryServerIndex.min.js.map
    extension-tao-delivery/views/js/loader/taoDelivery.min.js.map
    extension-tao-delivery/views/js/loader/taoDelivery.min.js

Suggestion is to replace is with <https://www.npmjs.com/package/lodash.throttle>

**TODO**: testing instructions. I need to specify how to install this ext and test it

### CODE REVIEW

**Comment by oatymart** [comment]
Don't forget to target `develop` branch.

**Review by oatymart — COMMENTED** [review]
Looks good so far. `taoDelivery` controller still works in TAO Community for launching tests.

I'd be ok with you replacing `_.throttle` with an alternative, as long as it's done following a global plan that is commonly agreed.

**Review by oatymart — APPROVED** [review]
Ok for me.

- [ ] New code is covered by tests (if applicable)
- [x] Tests are running successfully (old and new ones) on my local machine (if applicable)
- [x] New code is respecting code style rules
- [x] New code is respecting best practices
- [x] Feature is working correctly on my local machine (if applicable)
- [x] Acceptance criteria are respected
- [x] Pull request title and description are meaningful
- [x] Pull request's target is not `master`
- [ ] ~~Bundled code is present if needed~~
- [ ] ~~Version bump is applied if needed~~
- [x] Commits are following [conventional commits](https://www.conventionalcommits.org/en/v1.0.0/)
- [x]  Commits messages are meaningful
- [x] Commits are atomic
- [ ] ~~Changelog is updated according to changes (if applicable)~~
- [ ] Documentation is updated according to changes (if applicable)

**Review by wazelin — APPROVED** [review]
- [ ] New code is covered by tests (if applicable)
- [x] Tests are running successfully (old and new ones) on my local machine (if applicable)
- [x] New code is respecting code style rules
- [x] New code is respecting best practices
- [x] New code is not subject to concurrency issues (if applicable)
- [ ] Feature is working correctly on my local machine (if applicable)
- [x] Acceptance criteria are respected
- [x] Pull request title and description are meaningful
- [x] Pull request's target is not `master`

**Pull request merged**
