### PR TITLE
Tao 1908 testrunner adapter

### PR DESCRIPTION
**Pull request by jsconan**
Use an adapter to load the test runner.
Add an adapter to load the legacy test runner.
Add an adapter to load the new test runner.

### CODE REVIEW

**Comment by krampstudio** [comment]
From my perspective this is correct, the following points needs to be checked by @jbout : 
 - shouldn't `adapters` placed under the model folder ?
 - does this interfere with the theming, or the overriding of the delivery templates (like in `taoMp` ? )

**Comment by krampstudio** [comment]
reassigning to @jbout for verifications, but then I'll proceed to some testing

**Comment by jsconan** [comment]
Names changed:
TestRunnerAdapterInterface -> DeliveryContainer
TestRunnerLegacyAdapter -> DeliveryServiceContainer
TestRunnerAdapter -> DeliveryClientContainer
content-adapter -> content-loader

**Comment by jsconan** [comment]
Adapter changed to view renderers

**Comment by jbout** [comment]
The home button (upper right corner) is no longer working

**Pull request merged**
