### PR TITLE
Refactor/authorization

### PR DESCRIPTION
**Pull request by jbout**

### CODE REVIEW

**Comment by krampstudio** [comment]
It looks fine. Could you reassign it to someone else for code review and testing ? 
We also need to ensure this version isn't installed along with taoProctoring until we adapt it.

**Comment by krampstudio** [comment]
By the way, the unit tests should be adapted.

**Comment by bugalot** [comment]
Will review @krampstudio !

**Comment by bugalot** [comment]
@jbout @krampstudio 

No specific issue on TAO Verbatim, nothing in logs, update script OK.

Agrees with approach.

**Pull request merged**
